site_name: Dagpenger
repo_url: https://github.com/navikt/dp-dokumentasjon
site_url: https://navikt.github.com/dp-dokumentasjon
edit_uri: edit/main/docs/
theme:
  name: material
  logo: https://cdn.nav.no/teamdagpenger/dp-produktside-frontend/_next/static/media/static-dagpenger.1fd8010d.svg
  #logo: media/sign-document-icon.svg
  palette:
    primary: white
    
  # # Palette toggle for light mode
  # - media: "(prefers-color-scheme: light)"
  #   scheme: default
  #   primary: blue grey
  #   accent: deep purple
  #   toggle:
  #     icon: material/brightness-7
  #     name: Switch to dark mode
  # # Palette toggle for dark mode
  # - media: "(prefers-color-scheme: dark)"
  #   scheme: slate
  #   primary: blue grey
  #   accent: light blue
  #   toggle:
  #     icon: material/brightness-4
  #     name: Switch to light mode
  features:
    - content.action.edit
    - content.code.copy
    - content.code.annotate
  #  - content.tabs.link
  #  - navigation.footer
    - navigation.instant
   # - navigation.tabs
    - navigation.indexes
    - search.suggest
    - search.highlight
    - search.share
  icon:
    edit: material/pencil
    view: material/eye
    repo: fontawesome/brands/github
copyright: Made with ❤️ by Dagpengeklynga
plugins:
  - search
  - drawio_file
  - mermaid2
markdown_extensions:
  - toc:
      permalink: True
  - admonition
  - pymdownx.details
  - pymdownx.caret
  - pymdownx.tilde
  - pymdownx.superfences:
      preserve_tabs: true
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      use_pygments: true
      linenums_style: pymdownx-inline
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tasklist
  - pymdownx.smartsymbols
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - def_list
  - attr_list
  - footnotes
  - md_in_html
  - pymdownx.tasklist:
      custom_checkbox: true
extra:
  generator: false
nav:
  - Team innbyggerflate:
    - Prinsipper: innbyggerflater/prinsipper.md
    - Oversikt: innbyggerflater/index.md
    - Søknadsdialog: innbyggerflater/soknad.md
    - nav.no: innbyggerflater/nav-no.md
    - Meldeplikt: innbyggerflater/meldeplikt.md
    - Rapportering: innbyggerflater/rapportering.md 
      