site_name: Dagpenger - teknisk dokumentasjon
repo_url: https://github.com/navikt/dp-dokumentasjon
site_url: https://navikt.github.io/dp-dokumentasjon/
edit_uri: edit/main/docs/
theme:
  name: material
  logo: https://cdn.nav.no/teamdagpenger/dp-produktside-frontend/_next/static/media/static-dagpenger.1fd8010d.svg
  palette:
    primary: white
 
  features:
    - content.action.edit
    - content.code.copy
    - content.code.annotate
    - navigation.indexes
    - search.suggest
    - search.highlight
    - search.share
  icon:
    edit: material/pencil
    view: material/eye
    repo: fontawesome/brands/github
copyright: ""
plugins:
  - search
  - glightbox
  - drawio_file
  - redirects:
      redirect_maps:
        'index.md': 'innbyggerflater/README.md'

markdown_extensions:
  - toc:
      permalink: True
  - admonition
  - pymdownx.details
  - pymdownx.caret
  - pymdownx.tilde
  - pymdownx.superfences:
      preserve_tabs: true
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      use_pygments: true
      linenums_style: pymdownx-inline
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tasklist
  - pymdownx.smartsymbols
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
#      emoji_index: !!python/name:materialx.emoji.twemoji
#      emoji_generator: !!python/name:materialx.emoji.to_svg
  - def_list
  - attr_list
  - footnotes
  - md_in_html
  - pymdownx.tasklist:
      custom_checkbox: true
extra:
  generator: false
nav:
  - Innbyggerflate:
    - Om: innbyggerflater/README.md
    - Løsninger:
      - Systemkart: innbyggerflater/systemkart.md
      - Søknadsdialog: innbyggerflater/soknad.md
      - nav.no: innbyggerflater/nav-no.md
      - Meldeplikt: innbyggerflater/meldeplikt.md
      - Rapportering: innbyggerflater/rapportering.md
    - Prinsipper:
      - Kodekvalitet: innbyggerflater/kodekvalitet.md
